[default]

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = "db.sqlite3"
db_echo = false

[database]

db_type = "postgres"
db_drivername = "postgresql+psycopg2"
db_username = "postgres"
# Set in .secrets.toml
# db_password = ""
# db_host = "192.168.1.16"
db_host = "127.0.0.1"
db_port = 5432
db_database = "weather_dev"
db_echo = false

# db_type = "sqlite"
# db_drivername = "sqlite+pysqlite"
# db_username = ""
# # Set in .secrets.toml
# # db_password = ""
# db_host = ""
# db_port = ""
# db_database = "db.sqlite3"
# db_echo = false
